version: '3.4'

services:


  

  stbeverywhereespaceclientdb:
    container_name: StbEverywhereEspaceClientdb
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports: 
      - "1433:1433"
    
  

  
  stbeverywhereapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=stbeverywhereespaceclientdb;Database=STBEverywhereEspaceClient;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"

    depends_on:
      - stbeverywhereespaceclientdb
    restart: always
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro






   
  






 