version: '3.4'

services:
 


  stbeverywhereapi:
    image: ${DOCKER_REGISTRY-}stbeverywhereapi
    build:
      context: .
      dockerfile: Services/STBEverywhere/STBEverywhere.API/Dockerfile



  stbeverywhereespaceclientdb:
    image: mcr.microsoft.com/mssql/server


 