version: '3.4'

services:
  stbeverywhere.api:
    image: ${DOCKER_REGISTRY-}stbeverywhereapi
    build:
      context: .
      dockerfile: Services/STBEverywhere/STBEverywhere.API/Dockerfile

  emailservice.api:
    image: ${DOCKER_REGISTRY-}emailserviceapi
    build:
      context: .
      dockerfile: Services/Email/EmailService.API/Dockerfile
    restart: always


  smsnotifaction:
    image: ${DOCKER_REGISTRY-}smsnotifaction
    build:
      context: .
      dockerfile: Services/SMSMicroservices/SmsNotifaction/Dockerfile
    restart: always

  stbeverywhereespaceclientdb:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:3-management-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2

volumes:
  elasticsearch-data:
  sqlserverdata:


